### ISSUE TITLE
Withdrawal transaction should use fee estimator

### ISSUE THREAD

**Issue by drupalnomad** [vinumeris/lighthouse#142] opened 2015-01-26 08:08 UTC
I emptied my wallet, but the fee is 0.00001 so it is taking too long to confirm.

At the time of writing bitcoin-cli estimatefee 1 returns 0.00077821 which is 77 times greater.

It would be great if Lighthouse could use the fee estimator so that transactions get into the next block.

**Comment by mikehearn** [comment] 2015-01-26 21:47
The Bitcoin Core fee estimator produces garbage results, so the 77x figure doesn't mean much.

When you say "too long to confirm" how long was too long. How long did it take, in the end and how long did you want it to take?

**Comment by drupalnomad** [comment] 2015-01-27 05:00
It took 204 minutes: https://blockchain.info/tx/186e706ac5f8ce7ebbf4947b0da5174b578d71fa0f4c0da9ddd9929665cf2df7

I wanted it to be in the next block.

Do you know when the estimator will be working correctly? Are we supposed to round up the size to the next kilobyte boundary before multiplying by the fee?

**Comment by mikehearn** [comment] 2015-01-27 14:03
The fee paid on that tx is identical to the fee paid on the two input txns, which confirmed much faster. I think the issue here is that the previous blocks were either abnormally large (i.e. they hit the 1mb limit) or abnormally small, so the Bitcoin network itself was hitting capacity. When that happens *some* people have to wait until block space frees up. Unless you had some extremely pressing need for the transaction to confirm immediately, you would have had to attach a much larger fee to try and outcompete other people in the next block and if we wallet authors just keep adjusting the default fee upwards, other people would also start paying more simultaneously, so it wouldn't make much difference (this is a slightly theoretical argument but you get the idea).

In the future we'll have sliders to let people pick how much they care about confirming soon, but really, the solution here is to raise the block size limit. There's no other solution that makes everyone happen.

**Comment by mikehearn** [comment] 2015-01-28 15:32
Closing this as a duplicate of issue #46

**Closed by mikehearn** 2015-01-28 15:32 UTC

**Comment by drupalnomad** [comment] 2015-01-28 15:56
Thanks for the info!
