### ISSUE TITLE
Cover images displaying with incorrect colors

### ISSUE THREAD

**Issue by BashCo** [vinumeris/lighthouse#162] opened 2015-03-03 20:16 UTC
When attaching a cover image to a new project, the image is displayed with incorrect colors. 

To reproduce:

1. Create new project.
2. Add cover image, click next.
3. Click back, and notice the color of the image is completely different than the original.

**Comment by javgh** [comment] 2015-03-03 23:47
I am having the same issue here - both on a Linux machine and a Mac. Some screenshots:

Directly after adding the cover it is displayed correctly:

![colorproblem1](https://cloud.githubusercontent.com/assets/747896/6475136/80fa1380-c207-11e4-856f-5f13114c75f3.png)

After clicking next and going back it looks like this:

![colorproblem2](https://cloud.githubusercontent.com/assets/747896/6475153/8f4dc954-c207-11e4-998d-dc64fe0e0b49.png)

After saving the project it is displayed like this in the main list:

![colorproblem3](https://cloud.githubusercontent.com/assets/747896/6475162/a1454b50-c207-11e4-8de1-c60da4da5c98.png)

I tried with different types of images and with different formats (jpg, png and gif) but got always the same result.

**Comment by mikehearn** [comment] 2015-03-04 00:00
Yeah, it's obviously applying the random recolouring on that codepath, when it's only meant to be used for the default image. I'll fix it soon.

**Comment by BashCo** [comment] 2015-03-05 16:42
Will the fix apply to previous projects exhibiting recoloured images, or only future projects?

**Comment by mikehearn** [comment] 2015-03-05 19:29
Fixed - this turned out to have a different cause than what I expected. It's a regression that was created in the last update, which I didn't notice because I was using a different JVM than the version that is available for download and it's fixed in that newer version (noob error).

Unfortunately projects with the broken images need to be edited and have the image on them reset :( Sorry. I will push an update with the fix soon, perhaps this afternoon PST.

**Comment by javgh** [comment] 2015-03-06 16:16
I can confirm that this works correctly now for me in the latest version - thanks for the quick fix!

**Comment by mikehearn** [comment] 2015-03-06 16:17
Update pushed

**Closed** 2015-03-06 16:17 UTC
Labels: ui
