### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by nandubatchu** [vinumeris/lighthouse#138] opened 2015-01-23 04:34 UTC
Is there going to be an Android version released in near future?

**Comment by mikehearn** [comment] 2015-01-24 16:52
Not unless someone makes one or I get paid to do it. An Android version would be able to re-use most of the code I think, if we ported it backwards from Java 8 to Java 6.

**Comment by mikehearn** [comment] 2015-01-29 20:46
Duplicate of issue #49

**Closed by mikehearn** 2015-01-29 20:46 UTC
