### ISSUE TITLE
Integrate authorization

### ISSUE THREAD

**Issue by andychase** [vinumeris/lighthouse#197] opened 2015-08-28 00:18 UTC
Lighthouse should perform some sort of automated authorization to protect campaigns against forgery. Perhaps the `.lighthouse` file should contain some sort of signature that is signed by a X.509 certificate, or even better a gpg key that's authorized by data from https://keybase.io

Using a keybase.io key allows pledgers to see all the social media accounts associated with that key which builds up trust in a rigid and verifiable way.

**Comment by mikehearn** [comment] 2015-08-28 12:23
Duplicate of issue #54

**Closed by mikehearn** 2015-08-28 12:23 UTC
